config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get 'home/about' => 'homes#about', as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title, presence: true
  validates :body, presence: true,
            length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]  #ログイン認証されていなければ、ログイン画面へリダイレクトする
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  # emailの値も認証に使えるようにする
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment_new = BookComment.new
    @comment.save
    redirect_to request.referer
  end

  def destroy
    comment = BookComment.find(params[:id])
    @book = Book.find(params[:book_id])
    @comment_new = BookComment.new
    comment.destroy
    redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @user = User.find(current_user.id) #ログインしているユーザー
    @book = Book.new #新規投稿の部分テンプレート
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user #URLを入力しても画面に飛ばせない
      render "edit"
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have created book successfully.'  #詳細表示画面
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render "index"
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer # 同じ画面に遷移
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/uesrs_controller.rb
class UesrsController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.id = current_user.id
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(@user) do %>
        <%= image_tag book_comment.user.get_profile_image(40, 40) %>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <td><% if current_user.id == book_comment.user_id %>
          <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger btn-sm" %>
        <% end %>
    </td>
  </tr>
<% end %>

app/views/book_comments/_comment_form.html.erb
<%= form_with(model:[book, comment], id: "new_comment") do |f| %>
  <%= f.text_area :comment, rows: '5', class: "form-control" %>
  <div class="actions row">
    <%= f.submit "送信", class: "form_submit, btn btn-light" %>
  </div>
<% end %>

app/views/books/_newbook.html.erb
<h2>New book</h2>
<%= form_with model:book, local:true do |f| %>

  <h6>Title</h6>
  <%= f.text_field :title %>

  <h6>Opinion</h6>
  <%= f.text_area :body %>

  <div class="actions row">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div>
  <div class="container">
    <div class="col-sm-12 col-md8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>Editing Book</h2>

      <% if @book.errors.any? %>
        <h4><%= @book.errors.count %> error prohibited this obj from being saved:</h4>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <!--投稿編集フォーム-->
      <%= form_with model:@book, local:true do |f| %>
        <div class="field row">
          <%= f.label :Title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="field row">
          <%= f.label :Opinion %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="actions row">
          <%= f.submit class: "btn btn-success" %>
        </div>

        <div class="link">
          <%= link_to "Show", book_path(@book.id) %>
          <%= "  |  " %>
          <%= link_to "Back", books_path %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">

    <% if @book.errors.any? %>
      <h4><%= @book.errors.count %> error prohibited this obj from being saved:</h4>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="row">

      <div class="col-md-3">
        <%= render 'users/userinfo', user: @user %> <!--User infoの部分テンプレート-->
        <%= render 'books/newbook', book: @book %> <!--New bookの部分テンプレート-->
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th><!--ユーザーのプロフィールイメージ--></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= image_tag book.user.get_profile_image(40, 40) %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>

                <!--いいねの部分テンプレート-->
                <td>
                  <%= render 'favorites/favorite', book: book %>
                </td>

                <td>
                  コメント数: <%= book.book_comments.count %>
                </td>

              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="body">
  <div class="container">



    <div class="row">
      <div class="col-md-3">
        <%= render 'users/userinfo', user: @user %> <!--User infoの部分テンプレート-->
        <%= render 'books/newbook', book: @book_new %> <!--New bookの部分テンプレート-->
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= image_tag @book.user.get_profile_image(80, 80) %>
                  <%= @user.name %>
                <% end %>
              </td>

              <td>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
                <%= @book.body %>
              </td>

              <!--いいねの部分テンプレート-->
              <td>
                <%= render 'favorites/favorite', book: @book %>
              </td>

              <td>
                コメント数：<%= @book.book_comments.count %>
              </td>

              <td>
                <% if @book.user == current_user %>
                  <%= link_to edit_book_path(@book), class: "btn btn-sm btn-success" do %>
                    Edit
                  <% end %>
                <% end %>
              </td>

              <td>
                <% if @book.user == current_user %>
                  <%= link_to book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger" do %>
                    Destroy
                  <% end %>
                <% end %>
              </td>

            </tr>
          </tbody>
        </table>

        <!--コメントの表示-->
        <table>
          <tbody id="comment_area">
            <%= render 'book_comments/comment', book: @book %>
          </tbody>
        </table>

        <!--コメント入力フォーム-->
        <div  id="comment_form">
          <%= render 'book_comments/comment_form', book: @book, comment: @comment %>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>

    <%= link_to book_favorites_path(book), method: :delete, :style => "color:red;" do %>
      <i class="fa fa-heart"></i>
      <%= book.favorites.count %>
    <% end %>

<% else %>

    <%= link_to book_favorites_path(book), method: :post, :style => "color:blue;" do %>
     <i class="fa fa-heart"></i>
     <%= book.favorites.count %>
    <% end %>

<% end %>

app/views/homes/about.html.erb
<h1 class="px-3 mx-auto text-center">
  Welcome to
  <i class="fas fa-book"></i>
  <strong>Bookers</strong>
  !
</h1>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
	  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
		  <h1>
		    Welcom to
		    <i class="fas fa-book"></i>
		    <strong>Bookers</strong>
		    !!
		  </h1>
		<p>In
		  <i class="fas fa-book"></i>
		  <strong>Bookers</strong>
		  ,
		<p>
		  you can share and exchange your opinions , inpresiions , and emotions<br>
		  about various books!
		</p>

    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
	    </div>
	    <div class="row">
	      <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
	    </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/342be92c86.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button"
          data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false"
          aria-label="Toggle navigation">  <!--data-target="navbarNavDropdownでドロップダウンリスト表示, aria-expanded="false"で折りたたみ-->
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">  <!--mlは, margin-left: autoと同じ効果-->

              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class: "btn btn-link text-white" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "btn btn-link text-white" do %>
                    <i class="fas fa-users"></i>
                    Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "btn btn-link text-white" do %>
                    <i class="fas fa-book-open"></i>
                    Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-link text-white" do %>
                    <i class="fas fa-sign-out-alt"></i>
                    Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "btn btn-link text-white" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "btn btn-link text-white" do %>
                    <i class="fas fa-link"></i>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "btn btn-link text-white" do %>
                    <i class="fas fa-user-plus"></i>
                    Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "btn btn-link text-white" do %>
                    <i class="fas fa-sign-in-alt"></i>
                    Log in
                  <% end %>
                </li>
              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="body">
      <p class="notice"><%= notice %></p>

      <%= yield %>
      <footer>
        <div class="container mt-5 add">
          <div class="row">
            <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>

</html>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
  <%= image_tag user.get_profile_image(100, 100) %>

  <table class="table">
    <tbody>
      <tr>
        <th>name</th>  <!--ユーザー名-->
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>  <!--自己紹介-->
        <th><%= user.introduction %></th>
      </tr>

    </tbody>
  </table>

  <div class="row">  <!--editの画面へ-->
    <%= link_to edit_user_path(user), class: "col-xs-12 btn btn-outline-secondary btn-block form-control" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <% if @user.errors.any? %>
          <h4><%= @user.errors.count %> error prohibited this obj from being saved:</h4>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <!--プロフィール編集フォーム-->
        <%= form_with model:@user, local:true do |f| %>
          <div class="field row">
            <%= f.label :Name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="field row">
            <%= f.label :Image %>
            <%= f.file_field :profile_image, placeholder: "Image", class: "form-control-file" %>
          </div>
          <div class="field row">
            <%= f.label :Introduction %>
            <%= f.text_area :introduction, class: "form-control" %>
          </div>
          <div class="actions row">
            <%= f.submit class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/userinfo', user: @user %> <!--User infoの部分テンプレート-->
        <%= render 'books/newbook', book: @book %> <!--New bookの部分テンプレート-->
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th><!--showの部分--></th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= image_tag user.get_profile_image(80, 80) %>
                </td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body">
  <div class="container">

    <div class="row">
      <div class="col-md-3">
        <%= render 'users/userinfo', user: @user %> <!--User infoの部分テンプレート-->
        <%= render 'books/newbook', book: @book %> <!--New bookの部分テンプレート-->
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th><!--ProfileImage--></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= image_tag @user.get_profile_image(80, 80) %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book) %></td> <!--book_path(詳細表示)で(|book|)の投稿(.id)を持ってくる-->
                <td><%= book.body %></td>
                <!--いいねの部分テンプレート-->
                <td>
                  <%= render 'favorites/favorite', book: book %>
                </td>
                <td>コメント数：<%= book.book_comments.count %></td>
              </tr>
            <% end %>
          </tbody>

        </table>
      </div>
    </div>
  </div>
</div>